### ISSUE TITLE
(Relesed version 1.3.7) Does not build with Copperspice 1.7.4

### ISSUE THREAD

**Issue by adriaandegroot** [copperspice/diamond#23]
> I can't tell if Copperspice 1.7.4 is actually released; there's a tag, but it's not listed as a release on the GH page, nor are there tarballs. So this might be chasing ahead of things.

In CopperSpirce 762c02aa9c71c85bdb1c5cb1ce711085a97e1017,

```
commit 762c02aa9c71c85bdb1c5cb1ce711085a97e1017
Author: Barbara Geller <barbara@copperspice.com>
Date:   Thu Feb 10 16:05:18 2022 -0800

    Remove redundant enum Qt::Modifier, replace with Qt::KeyboardModifier
```

The modifier `Qt::CTRL` was removed, but this is used in several places in the Diamond codebase. Example build failures:

```
diamond-cs-1.3.7_2/src/dialog_macro.cpp:172:19: error: no member named 'SHIFT' in 'Qt'
         case Qt::SHIFT:
              ~~~~^
diamond-cs-1.3.7_2/src/dialog_macro.cpp:176:19: error: no member named 'CTRL' in 'Qt'
         case Qt::CTRL:
              ~~~~^
diamond-cs-1.3.7_2/src/dialog_macro.cpp:180:19: error: no member named 'META' in 'Qt'
         case Qt::META:
```

**Comment by adriaandegroot** [comment]
.. this is fixed in Diamond aeca606910d28cb9b1007e840a09dd6af3e1dc94 , but it might warrant a new Diamond release to reduce surprises.

**Comment by bgeller** [comment]
Any time we add a new tag and update the version then please consider this a new release.  CopperSpice1.7.4 was released with ec30095de. The new binary and source files were uploaded to our download page.  

We were not able to upload binary files due to a browser/AV issue.  This has been resolved and the uploads are now happening. 

A new version of Diamond is set to be released next week. 

Barbara
